### Get All
GET http://localhost:3000/v1/transfers/getAll HTTP/1.1
Content-Type: application/json

{}

### Get one by ID
GET http://localhost:3000/v1/transfers/getOne/1 HTTP/1.1
Content-Type: application/json

{}

### Create
POST http://localhost:3000/v1/transfers/create HTTP/1.1
Content-Type: application/json

{
    "userId": "2",
    "sender": "Andres",
    "recipient":"Alex",
    "amount": 850000
}

### Update
PUT  http://localhost:3000/v1/transfers/update/2 HTTP/1.1
Content-Type: application/json

{
    "amount": 650000
}

### Delete
DELETE  http://localhost:3000/v1/transfers/delete/2 HTTP/1.1
Content-Type: application/json

{}